### ISSUE TITLE
I got KeyError: 'SUNSKY' when I run it

### ISSUE THREAD

**Issue by nadershehata95** [progressify/pysunsky#5]
Hey I got this error when I ran it

```
(venv) D:\Work\Freelancer\SunSky-Get-Products-Data\pysunsky-master>python -m unittest tests.test_api_service.TestApi
Traceback (most recent call last):
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\unittest\__main__.py", line 18, in <module>
    main(module=None)
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\unittest\main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 220, in loadTestsFromNames 
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName  
    module = __import__(module_name)
  File "D:\Work\Freelancer\SunSky-Get-Products-Data\pysunsky-master\tests\test_api_service.py", line 81, in <module>    
    api.setUp()
  File "D:\Work\Freelancer\SunSky-Get-Products-Data\pysunsky-master\tests\test_api_service.py", line 18, in setUp
    self.oas = OpenApiService()
  File "D:\Work\Freelancer\SunSky-Get-Products-Data\pysunsky-master\pysunsky\api.py", line 20, in __init__
    self.key = config["SUNSKY"]["key"]
  File "C:\Users\nader\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 964, in __getitem__
    raise KeyError(key)
KeyError: 'SUNSKY'
```
I used my credentials in the config.ini file and also used the test credentials 
```
[SUNSKY]
key = TESTKEY
secret = TESTSECRET
```
and get the same error any help?

**Comment by progressify** [comment]
Please, share the tree of your folder or tell me your `config.ini` file location.
As you can read in the [REAMDE.md](https://github.com/progressify/pysunsky/blob/ded99c9846e2d1f519057bf1abec9dd93b2663c8/readme.md?plain=1#L42) the `config.ini` must to go in the folder where you execute the command.

**Comment by nadershehata95** [comment]
> Please, share the tree of your folder or tell me your `config.ini` file location. As you can read in the [REAMDE.md](https://github.com/progressify/pysunsky/blob/ded99c9846e2d1f519057bf1abec9dd93b2663c8/readme.md?plain=1#L42) the `config.ini` must to go in the folder where you execute the command.

![image](https://github.com/progressify/pysunsky/assets/103794068/8d7dcf9f-3cc7-4b44-934e-eb0fc44279fa)

**Comment by nadershehata95** [comment]
> Please, share the tree of your folder or tell me your `config.ini` file location. As you can read in the [REAMDE.md](https://github.com/progressify/pysunsky/blob/ded99c9846e2d1f519057bf1abec9dd93b2663c8/readme.md?plain=1#L42) the `config.ini` must to go in the folder where you execute the command.

here it is 
![image](https://github.com/progressify/pysunsky/assets/103794068/c9decbcd-eb1e-4bea-ab6e-709d048db5e9)

**Comment by progressify** [comment]
Try to copy the `config.ini` file in the root of the project.

```
D:\Work\Freelancer\SunSky-Get-Products-Data\pysunsky-master
```

**Comment by nadershehata95** [comment]
> 

I did and it passed this error and gives this new error 

```
(venv) D:\Work\Freelancer\SunSky-Get-Products-Data\pysunsky-master>python -m unittest tests.test_api_service.TestApipython
TESTKEY
TESTSECRET
E
======================================================================
ERROR: TestApipython (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module 'tests.test_api_service' has no attribute 'TestApipython'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by progressify** [comment]
This is the right command:
```
python -m unittest tests.test_api_service.TestApi
```
Pay attention!!
> > 
> 
> I did and it passed this error and gives this new error
> 
> ```
> (venv) D:\Work\Freelancer\SunSky-Get-Products-Data\pysunsky-master>python -m unittest tests.test_api_service.TestApipython
> TESTKEY
> TESTSECRET
> E
> ======================================================================
> ERROR: TestApipython (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> AttributeError: module 'tests.test_api_service' has no attribute 'TestApipython'
> 
> ----------------------------------------------------------------------
> Ran 1 test in 0.000s
> 
> FAILED (errors=1)
> ```
